config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'units#index'
  get '/units', to: 'units#index'
  delete '/units', to: 'units#delete_data'
  get '/units/load', to: 'units#load_data'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/unit.rb
class Unit < ApplicationRecord
	validates_uniqueness_of :name
	
	def self.load_data(url)
		require 'brews_gem'
		response = BrewsGem::Breweries.call(url)
		success = []
		failures = []
		response.formatted_breweries.each do |x|
			exists = Unit.find_by_name(x["name"])
			next if exists.present? 
			un = Unit.new 
	  	un.price = x["price"]
	  	un.name = x["name"]
	  	un.description = x["description"]
	  	un.area = x["area"]
	  	un.uom = x["uom"]
  		if un.save 
    		success << un.name 
  		else
    		failures << un.name 
  		end
  	end
  	return [200, success, failures]
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

	def index 
		@units = Unit.all
	end

	def delete_data
		Unit.delete_all 
		respond_to do |format|
        format.json { render json: 200}
    end
	end

	def load_data
		Unit.load_data("https://api.openbrewerydb.org/breweries")
		respond_to do |format|
        format.json { render json: 200}
    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EtlStarterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script  src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    
    <script  src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
      var AUTH_TOKEN = $('meta[name=csrf-token]').attr('content');
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/units/index.html.erb
<div class="container-fluid mycontainer">
	<h4>Coolest breweries</h4>
	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
			<button class="btn btn-success" onclick="GetData()">Get Breweries</button>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
			<button class="btn btn-danger" onclick="DeleteData()">Delete Breweries </button>
		</div>
	</div>
	<table class="table table-striped mytable">
		<thead>
			<th>Name</th>
			<th>Beer Price</th>
			<th>Description</th>
			<th>Factory Size</th>
			<th>Unit of Measure</th>
		</thead>
		<tbody>
			<% @units.each do |u| %>
				<tr>
					<td><%= u.name %></td>
					<td>USD <%= u.price %></td>
					<td><%= u.description %></td>
					<td><%= u.area %></td>
					<td><%= u.uom %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div id="spinner" class=""></div>

<style>
.mycontainer{
	margin: 30px;
}
.mytable{
	margin-top: 20px;
}

.hm-spinner{
  height: 160px;
  width: 160px;
  border: 8px solid transparent;
  border-top-color: #9C27B0;
  border-bottom-color: #9C27B0;
  border-radius: 50%;
  position: fixed;
  -webkit-animation: spin 3s linear infinite;
          animation: spin 3s linear infinite;
  top:45%;
  left:45%;
  z-index: 999;
}

.hm-spinner::before{
  content: "";
  position: absolute;
  top: 20px;
  right: 20px;
  bottom: 20px;
  left: 20px;
  border: 6px solid transparent;
  border-top-color: #BA68C8;
  border-bottom-color: #BA68C8;
  border-radius: 50%;
  -webkit-animation: spin 1.5s linear infinite;
  animation: spin 1.5s linear infinite;
}

@-webkit-keyframes spin {
    from {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    to {
      -webkit-transform: rotate(360deg);
      transform: rotate(360deg);
    }
}

@keyframes spin {
    from {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
    }
    to {
      -webkit-transform: rotate(360deg);
      transform: rotate(360deg);
    }
}
</style>

<script>
function DeleteData(){
	$('#spinner').addClass('hm-spinner');
	$.ajax({
    type:"DELETE", 
    url:"<%= url_for units_path %>" , 
    data: { "authenticity_token": AUTH_TOKEN},
    dataType: 'json',
    success:function(result){  
    	// alert(result)
    	location.reload();
    },
    error:function(err){

    }
  });
};

function GetData(){
	$('#spinner').addClass('hm-spinner');
	$.ajax({
    type:"GET", 
    url:"<%= url_for units_load_path %>" , 
    data: { "authenticity_token": AUTH_TOKEN},
    dataType: 'json',
    success:function(result){  
    	// alert(result)
    	location.reload();
    },
    error:function(err){

    }
  });
};
</script>